title: "Shreyashwi's Data Science Portfolio"
description: "A portfolio showcasing my data science projects and skills."
theme: minima
social_links:
  LinkedIn: https://www.linkedin.com/in/shreyashwi/
